### ISSUE TITLE
Twitter client no longer works

### ISSUE THREAD

**Issue by mathewparet** [lbarchive/bash-oauth#1]
```
<?xml version="1.0" encoding="UTF-8"?>
<errors>
<error code="68">The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.</error>
</errors>
```

---

2014-01-10T19:17:21Z: edited by @livibetter for clearing up the issue, see also #2

**Comment by livibetter** [comment]
I don't use bash-oauth anymore since I stopped using Twitter, so this would have to be taken care by other. Feel free to submit a bugfix.

I quick looked through the API v1.1, `jq` might be a good candidate for parsing if the script really needs one. The library itself would have to be patched for revised OAuth if I am not mistaken.

**Comment by mathewparet** [comment]
I fixed it. Will upload the new code to get hub soon.
